### ISSUE TITLE
Failed to load the QuickMenu package

### ISSUE THREAD

**Issue by webmestre-comeul** [spywhere/AtomQuickMenu#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.1
**Thrown From**: [QuickMenu](https://github.com/spywhere/AtomQuickMenu) package, v0.2.2
### Stack Trace

Failed to load the QuickMenu package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/webdev/.atom/packages/quickmenu/lib/atom-quick-menu-dialog.coffee:1:1)
    at /Users/webdev/.atom/packages/quickmenu/lib/atom-quick-menu-dialog.coffee:5:3
    at Object.<anonymous> (/Users/webdev/.atom/packages/quickmenu/lib/atom-quick-menu-dialog.coffee:5:3)
    at Object.<anonymous> (/Users/webdev/.atom/packages/quickmenu/lib/atom-quick-menu-dialog.coffee:1:1)
    at Module._compile (/Users/webdev/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Users/webdev/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/webdev/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/webdev/.atom/packages/quickmenu/lib/atom-quick-menu.coffee:1:23)
    at Object.<anonymous> (/Users/webdev/.atom/packages/quickmenu/lib/atom-quick-menu.coffee:1:1)
    at Module._compile (/Users/webdev/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Users/webdev/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/webdev/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/webdev/.atom/packages/quickmenu/lib/atom-quick-menu-main.coffee:2:17)
    at Object.<anonymous> (/Users/webdev/.atom/packages/quickmenu/lib/atom-quick-menu-main.coffee:2:1)
    at Module._compile (/Users/webdev/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Users/webdev/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/webdev/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Users/webdev/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:720:27)
    at /Users/webdev/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:116:28
    at Package.module.exports.Package.measure (/Users/webdev/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/Users/webdev/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Users/webdev/Downloads/Atom.app/Contents/Resources/app.asar/src/package-manager.js:445:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Users/webdev/Downloads/Atom.app/Contents/Resources/app.asar/src/package-manager.js:524:30)
    at /Users/webdev/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:444:29
    at exit (/Users/webdev/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Users/webdev/Downloads/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at /Users/webdev/Downloads/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
    at Socket.<anonymous> (/Users/webdev/Downloads/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```
### Commands

```
  5x -0:20.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:18 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-light-ui",
      "naturezen-light-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
QuickMenu, v0.2.2
auto-indent, v0.5.0
linter, v1.11.3
linter-php, v1.1.8
naturezen-light-syntax, v0.1.0

# Dev
No dev packages
```

**Comment by spywhere** [comment]
That's expectable at the moment. This plugin did not continue in development for a very long time (at least after Atom has sent invitation to me). This package is not aims for Atom's users, rather for Atom's developer who wants to make the menu panel works just like Sublime Text with ability to use submenu and various features on the QuickMenu repo itself.

If you still want this package to continue, just notice me and I will allocate a time for this project later on :)
